DROP TABLE MEDIA.DIRECTORY;
CREATE TABLE MEDIA.DIRECTORY
(
  ID CHARACTER VARYING(19) NOT NULL
    PRIMARY KEY,
  DIR_CODE INTEGER NOT NULL,
  PARENT_CODE INTEGER NOT NULL,
  NAME CHARACTER VARYING(500) DEFAULT '' NOT NULL,
  PATH VARCHAR(1000) DEFAULT '' NOT NULL,
  CODE_LIST CHARACTER VARYING(100) DEFAULT '' NOT NULL,
  LEVEL TINYINT DEFAULT '0' NOT NULL,
  DELETE_STATUS TINYINT DEFAULT '0' NOT NULL,
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP,
  DELETE_TIME TIMESTAMP
);

COMMENT ON TABLE MEDIA.DIRECTORY IS '资源目录';

COMMENT ON COLUMN MEDIA.DIRECTORY.ID IS '主键ID';

COMMENT ON COLUMN MEDIA.DIRECTORY.DIR_CODE IS '目录代码';

COMMENT ON COLUMN MEDIA.DIRECTORY.PARENT_CODE IS '父目录代码';

COMMENT ON COLUMN MEDIA.DIRECTORY.NAME IS '目录名';

COMMENT ON COLUMN MEDIA.DIRECTORY.PATH IS '全路径';

COMMENT ON COLUMN MEDIA.DIRECTORY.CODE_LIST IS '全路径对用的目录代码清单';

COMMENT ON COLUMN MEDIA.DIRECTORY.LEVEL IS '目录层级';

COMMENT ON COLUMN MEDIA.DIRECTORY.DELETE_STATUS IS '删除状态0未删除1删除';

COMMENT ON COLUMN MEDIA.DIRECTORY.CREATE_TIME IS '创建时间';

COMMENT ON COLUMN MEDIA.DIRECTORY.UPDATE_TIME IS '更新时间';

COMMENT ON COLUMN MEDIA.DIRECTORY.DELETE_TIME IS '删除时间';

CREATE UNIQUE INDEX MEDIA.MEDIA_DIRECTORY_1
  ON MEDIA.DIRECTORY (DIR_CODE);

CREATE INDEX MEDIA.MEDIA_DIRECTORY_2
  ON MEDIA.DIRECTORY (CODE_LIST);

CREATE TABLE MEDIA.DIR_REPO
(
  ID CHARACTER VARYING(19) NOT NULL
    PRIMARY KEY,
  DIR_CODE INTEGER NOT NULL,
  NAME CHARACTER VARYING(32) DEFAULT '' NOT NULL,
  PATH CHARACTER VARYING(500) DEFAULT '' NOT NULL,
  DELETE_STATUS TINYINT DEFAULT '0' NOT NULL,
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP,
  DELETE_TIME TIMESTAMP
);

COMMENT ON TABLE MEDIA.DIR_REPO IS '仓库表';

COMMENT ON COLUMN MEDIA.DIR_REPO.ID IS '主键ID';

COMMENT ON COLUMN MEDIA.DIR_REPO.DIR_CODE IS '目录代码';

COMMENT ON COLUMN MEDIA.DIR_REPO.NAME IS '名称（不是目录名）';

COMMENT ON COLUMN MEDIA.DIR_REPO.PATH IS '全路径';

COMMENT ON COLUMN MEDIA.DIR_REPO.DELETE_STATUS IS '删除状态';

COMMENT ON COLUMN MEDIA.DIR_REPO.CREATE_TIME IS '创建时间';

COMMENT ON COLUMN MEDIA.DIR_REPO.UPDATE_TIME IS '更新时间';

COMMENT ON COLUMN MEDIA.DIR_REPO.DELETE_TIME IS '删除时间';

CREATE UNIQUE INDEX MEDIA.DIR_REPO_1
  ON MEDIA.DIR_REPO (DIR_CODE);

ALTER TABLE MEDIA.RESOURCE
ADD COLUMN DIR_CODE INTEGER NOT NULL DEFAULT '0';

UPDATE MEDIA.RESOURCE
SET SAVE_TIME = CREATE_TIME
WHERE SAVE_TIME IS NULL;

ALTER TABLE MEDIA.RESOURCE
ALTER COLUMN SAVE_TIME SET NOT NULL;
