ALTER TABLE MEDIA.RESOURCE
DROP COLUMN DIR;

CREATE TABLE MEDIA.TAG
(
  ID VARCHAR(19) NOT NULL PRIMARY KEY,
  NAME VARCHAR(10) NOT NULL DEFAULT '',
  CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  DELETE_TIME TIMESTAMP
);

CREATE INDEX MEDIA.MEDIA_TAG_1 ON MEDIA.TAG (NAME);

COMMENT ON TABLE MEDIA.TAG IS '标签';
COMMENT ON COLUMN MEDIA.TAG.ID IS '主键';
COMMENT ON COLUMN MEDIA.TAG.NAME IS '名称';
COMMENT ON COLUMN MEDIA.TAG.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN MEDIA.TAG.DELETE_TIME IS '删除时间';

CREATE TABLE MEDIA.TAG_REFERENCE
(
  ID VARCHAR(19) NOT NULL PRIMARY KEY,
  RESOURCE_ID VARCHAR(19) NOT NULL DEFAULT '',
  TAG_ID VARCHAR(19) NOT NULL DEFAULT '',
  REFERENCE_TYPE TINYINT NOT NULL DEFAULT 0,
  REFER_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UN_REFER_TIME TIMESTAMP
);

CREATE INDEX MEDIA_TAG_REFERENCE_1 ON MEDIA.TAG_REFERENCE (RESOURCE_ID);
CREATE INDEX MEDIA_TAG_REFERENCE_2 ON MEDIA.TAG_REFERENCE (TAG_ID);

COMMENT ON TABLE MEDIA.TAG_REFERENCE IS '标签引用';
COMMENT ON COLUMN MEDIA.TAG_REFERENCE.ID IS '主键';
COMMENT ON COLUMN MEDIA.TAG_REFERENCE.RESOURCE_ID IS '资源ID';
COMMENT ON COLUMN MEDIA.TAG_REFERENCE.TAG_ID IS '标签ID';
COMMENT ON COLUMN MEDIA.TAG_REFERENCE.REFERENCE_TYPE IS '引用类型1:资源';
COMMENT ON COLUMN MEDIA.TAG_REFERENCE.REFER_TIME IS '引用时间';
COMMENT ON COLUMN MEDIA.TAG_REFERENCE.UN_REFER_TIME IS '取消引用的时间';
