# datasource
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: ${url}
    username: ${username}
    password: ${password}
mybatis-plus:
  config-location: classpath:configs/mybatis.xml
  mapper-locations: classpath:configs/mappers/**/*.xml