# todo 配置文件改造：xml -> yaml
spring:
  #  生产环境通过jvm参数传入，测试环境可以写明文
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./data/media.h2;AUTO_SERVER=TRUE
    username: media.h2
    password: media.h2
  h2:
    console:
      enabled: true
      path: /h2
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8