mybatis-plus:
  mapper-locations: classpath:configs/mappers/**/*.xml
  configuration:
    log-prefix: sql.
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true