# datasource
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:database.sqlite
mybatis-plus:
  config-location: classpath:configs/mybatis.xml
  mapper-locations: classpath:configs/mappers/**/*.xml

# server
server:
  servlet:
    context-path: /media