CREATE TABLE MEDIA.ALBUM
(
  ID CHARACTER VARYING(19) NOT NULL
    PRIMARY KEY,
  ALBUM_NAME CHARACTER VARYING(90) NOT NULL,
  AUTHOR_ID CHARACTER VARYING(19) NOT NULL,
  CREATE_TIME TIMESTAMP NOT NULL,
  UPDATE_TIME TIMESTAMP
);
COMMENT ON TABLE MEDIA.ALBUM IS '专辑';
COMMENT ON COLUMN MEDIA.ALBUM.ID IS 'ID';
COMMENT ON COLUMN MEDIA.ALBUM.ALBUM_NAME IS '专辑';
COMMENT ON COLUMN MEDIA.ALBUM.AUTHOR_ID IS '专辑作者';
COMMENT ON COLUMN MEDIA.ALBUM.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN MEDIA.ALBUM.UPDATE_TIME IS '更新时间';

CREATE TABLE MEDIA.AUTHOR
(
  ID CHARACTER VARYING(19) NOT NULL
    PRIMARY KEY,
  USER_ID CHARACTER VARYING(90),
  USERNAME CHARACTER VARYING(90) NOT NULL,
  SITE_ID CHARACTER VARYING(19) NOT NULL,
  HOMEPAGE CHARACTER VARYING(90),
  CREATE_TIME TIMESTAMP NOT NULL,
  UPDATE_TIME TIMESTAMP,
  DELETE_STATUS INTEGER DEFAULT 0 NOT NULL
);
COMMENT ON TABLE MEDIA.AUTHOR IS '创作人员';
COMMENT ON COLUMN MEDIA.AUTHOR.ID IS 'ID';
COMMENT ON COLUMN MEDIA.AUTHOR.USER_ID IS '用户在站点注册时的ID';
COMMENT ON COLUMN MEDIA.AUTHOR.USERNAME IS '用户名';
COMMENT ON COLUMN MEDIA.AUTHOR.SITE_ID IS '注册站点ID';
COMMENT ON COLUMN MEDIA.AUTHOR.HOMEPAGE IS '主页';
COMMENT ON COLUMN MEDIA.AUTHOR.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN MEDIA.AUTHOR.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN MEDIA.AUTHOR.DELETE_STATUS IS '删除状态0未删除1删除';
CREATE INDEX MEDIA.AUTHOR_1
  ON MEDIA.AUTHOR (USER_ID);
CREATE INDEX MEDIA.AUTHOR_2
  ON MEDIA.AUTHOR (USERNAME);
CREATE INDEX MEDIA.AUTHOR_3
  ON MEDIA.AUTHOR (SITE_ID);
CREATE INDEX MEDIA.AUTHOR_4
  ON MEDIA.AUTHOR (CREATE_TIME);
CREATE INDEX MEDIA.AUTHOR_5
  ON MEDIA.AUTHOR (UPDATE_TIME);

CREATE TABLE MEDIA.RESOURCE
(
  ID CHARACTER VARYING(19) NOT NULL
    PRIMARY KEY,
  FILENAME CHARACTER VARYING(90) NOT NULL,
  AUTHOR_ID CHARACTER VARYING(19) NOT NULL,
  ALBUM_ID CHARACTER VARYING(19),
  CREATE_TIME TIMESTAMP NOT NULL,
  UPDATE_TIME TIMESTAMP,
  SAVE_TIME TIMESTAMP,
  DELETE_STATUS INTEGER DEFAULT 0 NOT NULL
);
COMMENT ON TABLE MEDIA.RESOURCE IS '资源';
COMMENT ON COLUMN MEDIA.RESOURCE.ID IS 'ID';
COMMENT ON COLUMN MEDIA.RESOURCE.FILENAME IS '文件名';
COMMENT ON COLUMN MEDIA.RESOURCE.AUTHOR_ID IS '作者ID';
COMMENT ON COLUMN MEDIA.RESOURCE.ALBUM_ID IS '专辑ID';
COMMENT ON COLUMN MEDIA.RESOURCE.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN MEDIA.RESOURCE.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN MEDIA.RESOURCE.SAVE_TIME IS '保存时间';
COMMENT ON COLUMN MEDIA.RESOURCE.DELETE_STATUS IS '删除状态0未删除1删除';
CREATE INDEX MEDIA.RESOURCE_1
  ON MEDIA.RESOURCE (CREATE_TIME DESC);
CREATE INDEX MEDIA.RESOURCE_2
  ON MEDIA.RESOURCE (UPDATE_TIME DESC);
CREATE INDEX MEDIA.RESOURCE_3
  ON MEDIA.RESOURCE (FILENAME);

CREATE TABLE MEDIA.SITE
(
  ID CHARACTER VARYING(19) NOT NULL
    PRIMARY KEY,
  SITE_NAME CHARACTER VARYING(90) NOT NULL,
  URL CHARACTER VARYING(90) NOT NULL,
  CREATE_TIME TIMESTAMP NOT NULL,
  UPDATE_TIME TIMESTAMP,
  DELETE_STATUS INTEGER DEFAULT 0 NOT NULL
);
COMMENT ON TABLE MEDIA.SITE IS '站点';
COMMENT ON COLUMN MEDIA.SITE.ID IS 'ID';
COMMENT ON COLUMN MEDIA.SITE.SITE_NAME IS '网站名称';
COMMENT ON COLUMN MEDIA.SITE.URL IS '网站地址';
COMMENT ON COLUMN MEDIA.SITE.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN MEDIA.SITE.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN MEDIA.SITE.DELETE_STATUS IS '删除状态0未删除1删除';
CREATE INDEX MEDIA.SITE_1
  ON MEDIA.SITE (SITE_NAME);
CREATE INDEX MEDIA.SITE_2
  ON MEDIA.SITE (CREATE_TIME);
CREATE INDEX MEDIA.SITE_3
  ON MEDIA.SITE (UPDATE_TIME);

CREATE TABLE MEDIA.DIRECTORY
(
  ID VARCHAR(19) NOT NULL PRIMARY KEY,
  DIR_CODE INTEGER NOT NULL,
  PARENT_CODE INTEGER NOT NULL,
  NAME VARCHAR(500) NOT NULL DEFAULT '',
  CODE_LIST VARCHAR(50) NOT NULL DEFAULT '',
  LEVEL TINYINT NOT NULL DEFAULT '0',
  DELETE_STATUS TINYINT NOT NULL DEFAULT '0',
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  UPDATE_TIME TIMESTAMP,
  DELETE_TIME TIMESTAMP
);
COMMENT ON TABLE MEDIA.DIRECTORY IS '资源目录';
COMMENT ON COLUMN MEDIA.DIRECTORY.ID IS '主键ID';
COMMENT ON COLUMN MEDIA.DIRECTORY.DIR_CODE IS '目录代码';
COMMENT ON COLUMN MEDIA.DIRECTORY.PARENT_CODE IS '父目录代码';
COMMENT ON COLUMN MEDIA.DIRECTORY.NAME IS '目录名';
COMMENT ON COLUMN MEDIA.DIRECTORY.CODE_LIST IS '全路径对用的目录代码清单';
COMMENT ON COLUMN MEDIA.DIRECTORY.LEVEL IS '目录层级';
COMMENT ON COLUMN MEDIA.DIRECTORY.DELETE_STATUS IS '删除状态0未删除1删除';
COMMENT ON COLUMN MEDIA.DIRECTORY.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN MEDIA.DIRECTORY.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN MEDIA.DIRECTORY.DELETE_TIME IS '删除时间';
CREATE UNIQUE INDEX MEDIA.MEDIA_DIRECTORY_1 ON MEDIA.DIRECTORY (DIR_CODE);
CREATE INDEX MEDIA.MEDIA_DIRECTORY_2 ON MEDIA.DIRECTORY (CODE_LIST);


CREATE TABLE MEDIA.TAG
(
  ID VARCHAR(19) NOT NULL PRIMARY KEY,
  NAME VARCHAR(10) NOT NULL DEFAULT '',
  CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  DELETE_TIME TIMESTAMP
);
CREATE INDEX MEDIA.MEDIA_TAG_1 ON MEDIA.TAG (NAME);

COMMENT ON TABLE MEDIA.TAG IS '标签';
COMMENT ON COLUMN MEDIA.TAG.ID IS '主键';
COMMENT ON COLUMN MEDIA.TAG.NAME IS '名称';
COMMENT ON COLUMN MEDIA.TAG.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN MEDIA.TAG.DELETE_TIME IS '删除时间';

CREATE TABLE MEDIA.TAG_REFERENCE
(
  ID VARCHAR(19) NOT NULL PRIMARY KEY,
  RESOURCE_ID VARCHAR(19) NOT NULL DEFAULT '',
  TAG_ID VARCHAR(19) NOT NULL DEFAULT '',
  REFERENCE_TYPE TINYINT NOT NULL DEFAULT 0,
  REFER_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UN_REFER_TIME TIMESTAMP
);

CREATE INDEX MEDIA_TAG_REFERENCE_1 ON MEDIA.TAG_REFERENCE (RESOURCE_ID);
CREATE INDEX MEDIA_TAG_REFERENCE_2 ON MEDIA.TAG_REFERENCE (TAG_ID);

COMMENT ON TABLE MEDIA.TAG_REFERENCE IS '标签引用';
COMMENT ON COLUMN MEDIA.TAG_REFERENCE.ID IS '主键';
COMMENT ON COLUMN MEDIA.TAG_REFERENCE.RESOURCE_ID IS '资源ID';
COMMENT ON COLUMN MEDIA.TAG_REFERENCE.TAG_ID IS '标签ID';
COMMENT ON COLUMN MEDIA.TAG_REFERENCE.REFERENCE_TYPE IS '引用类型1:资源';
COMMENT ON COLUMN MEDIA.TAG_REFERENCE.REFER_TIME IS '引用时间';
COMMENT ON COLUMN MEDIA.TAG_REFERENCE.UN_REFER_TIME IS '取消引用的时间';
