-- ddl可用于mysql
DROP TABLE IF EXISTS RESOURCE_TYPE_MAP;
CREATE TABLE RESOURCE_TYPE_MAP(
    ID VARCHAR(19) NOT NULL   COMMENT '主键' ,
    PARENT_ID VARCHAR(19)    COMMENT '父类型' ,
    NAME VARCHAR(90) NOT NULL   COMMENT '名称' ,
    CREATE_TIME DATETIME NOT NULL   COMMENT '创建时间' ,
    UPDATE_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '资源类型映射';

DROP TABLE IF EXISTS RESOURCE;
CREATE TABLE RESOURCE(
    ID VARCHAR(19) NOT NULL   COMMENT 'ID' ,
    FILENAME VARCHAR(90) NOT NULL   COMMENT '文件名' ,
    DIR VARCHAR(900) NOT NULL   COMMENT '资源目录' ,
    AUTHOR_ID VARCHAR(19) NOT NULL   COMMENT '作者id' ,
    ALBUM_ID VARCHAR(19)    COMMENT '专辑id' ,
    CREATE_TIME DATETIME NOT NULL   COMMENT '创建时间' ,
    UPDATE_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '资源';

DROP TABLE IF EXISTS RESOURCE_TYPE;
CREATE TABLE RESOURCE_TYPE(
    ID VARCHAR(19) NOT NULL   COMMENT 'ID' ,
    RESOURCE_ID VARCHAR(19) NOT NULL   COMMENT '资源id' ,
    TYPE_ID VARCHAR(19) NOT NULL   COMMENT '类型id' ,
    CREATE_TIME DATETIME NOT NULL   COMMENT '创建时间' ,
    UPDATE_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '资源和类型关联';

DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(
    ID VARCHAR(19) NOT NULL   COMMENT 'ID' ,
    USER_ID VARCHAR(90)    COMMENT '用户在站点注册时的id' ,
    USERNAME VARCHAR(90) NOT NULL   COMMENT '用户名' ,
    SITE VARCHAR(19) NOT NULL   COMMENT '注册站点ID' ,
    HOMEPAGE VARCHAR(90) NOT NULL   COMMENT '主页' ,
    CREATE_TIME DATETIME NOT NULL   COMMENT '创建时间' ,
    UPDATE_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '创作人员';

DROP TABLE IF EXISTS SITE;
CREATE TABLE SITE(
    ID VARCHAR(19) NOT NULL   COMMENT 'ID' ,
    SITE_NAME VARCHAR(90) NOT NULL   COMMENT '网站名称' ,
    URL VARCHAR(90) NOT NULL   COMMENT '网站地址' ,
    CREATE_TIME DATETIME NOT NULL   COMMENT '创建时间' ,
    UPDATE_TIME DATETIME    COMMENT '更细时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '站点';

DROP TABLE IF EXISTS ALBUM;
CREATE TABLE ALBUM(
    ID VARCHAR(19) NOT NULL   COMMENT 'ID' ,
    ALBUM_NAME VARCHAR(90) NOT NULL   COMMENT '专辑' ,
    AUTHOR_ID VARCHAR(19) NOT NULL   COMMENT '专辑作者' ,
    CREATE_TIME DATETIME NOT NULL   COMMENT '创建时间' ,
    UPDATE_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '专辑';

DROP TABLE IF EXISTS RESOURCE_ALBUM;
CREATE TABLE RESOURCE_ALBUM(
    ID VARCHAR(19) NOT NULL   COMMENT 'ID' ,
    CREATE_TIME DATETIME NOT NULL   COMMENT '创建时间' ,
    UPDATE_TIME DATETIME    COMMENT '更新时间' ,
    RESOURCE_ID VARCHAR(19) NOT NULL   COMMENT '资源ID' ,
    ALBUM_ID VARCHAR(19) NOT NULL   COMMENT '专辑ID' ,
    PRIMARY KEY (ID)
)  COMMENT = '资源所属专辑';

