-- 已废弃，请使用h2.sql
DROP TABLE IF EXISTS RESOURCE_TYPE_MAP;
CREATE TABLE RESOURCE_TYPE_MAP(
    ID TEXT(19) NOT NULL  , --主键
    PARENT_ID TEXT(19)   , --父类型
    NAME TEXT(90) NOT NULL  , --名称
    CREATE_TIME NUMERIC NOT NULL  , --创建时间
    UPDATE_TIME NUMERIC   , --更新时间
    PRIMARY KEY (ID)
)  ; --资源类型映射

DROP TABLE IF EXISTS RESOURCE;
CREATE TABLE RESOURCE(
    ID TEXT(19) NOT NULL  , --ID
    FILENAME TEXT(90) NOT NULL  , --文件名
    DIR TEXT(900) NOT NULL  , --资源目录
    AUTHOR_ID TEXT(19) NOT NULL  , --作者id
    ALBUM_ID TEXT(19)   , --专辑id
    CREATE_TIME NUMERIC NOT NULL  , --创建时间
    UPDATE_TIME NUMERIC   , --更新时间
    PRIMARY KEY (ID)
)  ; --资源

DROP TABLE IF EXISTS RESOURCE_TYPE;
CREATE TABLE RESOURCE_TYPE(
    ID TEXT(19) NOT NULL  , --ID
    RESOURCE_ID TEXT(19) NOT NULL  , --资源id
    TYPE_ID TEXT(19) NOT NULL  , --类型id
    CREATE_TIME NUMERIC NOT NULL  , --创建时间
    UPDATE_TIME NUMERIC   , --更新时间
    PRIMARY KEY (ID)
)  ; --资源和类型关联

DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(
    ID TEXT(19) NOT NULL  , --ID
    USER_ID TEXT(90)   , --用户在站点注册时的id
    USERNAME TEXT(90) NOT NULL  , --用户名
    SITE TEXT(19) NOT NULL  , --注册站点ID
    HOMEPAGE TEXT(90) NOT NULL  , --主页
    CREATE_TIME NUMERIC NOT NULL  , --创建时间
    UPDATE_TIME NUMERIC   , --更新时间
    PRIMARY KEY (ID)
)  ; --创作人员

DROP TABLE IF EXISTS SITE;
CREATE TABLE SITE(
    ID TEXT(19) NOT NULL  , --ID
    SITE_NAME TEXT(90) NOT NULL  , --网站名称
    URL TEXT(90) NOT NULL  , --网站地址
    CREATE_TIME NUMERIC NOT NULL  , --创建时间
    UPDATE_TIME NUMERIC   , --更细时间
    PRIMARY KEY (ID)
)  ; --站点

DROP TABLE IF EXISTS ALBUM;
CREATE TABLE ALBUM(
    ID TEXT(19) NOT NULL  , --ID
    ALBUM_NAME TEXT(90) NOT NULL  , --专辑
    AUTHOR_ID TEXT(19) NOT NULL  , --专辑作者
    CREATE_TIME NUMERIC NOT NULL  , --创建时间
    UPDATE_TIME NUMERIC   , --更新时间
    PRIMARY KEY (ID)
)  ; --专辑

