name: pre-package
on:
  push:
    branches: [package-*]
jobs:
  clone-code:
    name: 拉取代码
    env:
      UI_BRANCH: build-0.2.0-alpha
      SERVER_BRANCH: package-0.2.1-alpha
    runs-on: ubuntu-latest
    steps:
      - name: 拉取前台代码
        run: |
          git clone --depth 1 -b $UI_BRANCH https://github.com/wrote-code/media-ui.git

      - name: 设置node环境
        uses: actions/setup-node@v3
        with:
          node-version: 14.17.6
          cache: yarn
          cache-dependency-path: media-ui/yarn.lock
          name: 编译前台代码

      - name: 编译前台代码
        run: |
          cd media-ui
          node -v
          npm -v
          yarn -v
          yarn install
          yarn build

      - name: 拉取后台代码
        run: |
          git clone --depth 1 -b $SERVER_BRANCH https://github.com/wrote-code/media.git

      - name: 设置java环境
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: maven

      - name: 复制前台产物到后static目录
        run: |
          cd media
          mkdir src/main/resources/static
          cp -r ../media-ui/dist src/main/resources/static

      - name: 编译后台代码
        run: |
          cd media
          mvn -v
          java -version
          mvn -B clean
          mvn -DskipTests=true -B package

      - name: 上传完整制品
        uses: actions/upload-artifact@v3
        with:
          name: 可执行jar包
          path: media/target/media-*.jar
